# -*- coding: utf-8 -*-
"""Assignment3 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YLCT4Rlz6gj18fy4XkKCUO11AUL2vUOV
"""

# TODO: Load the data into a DataFrame
import pandas as pd

# Replace the file path if needed
df = pd.read_csv('hourly_weather_10_days.csv')
df.head()

print(df.info())

print(df.describe())

print(df.isna().sum())

numeric_cols = ['temperature_C', 'humidity_%', 'wind_speed_kmph', 'pressure_hPa', 'visibility_km']

for col in numeric_cols:
    ## Forward Fill
    df[col] = df[col].ffill()

    df[col] = df[col].fillna(0)

print("\nAfter Filling:")
print(df[numeric_cols].isna().sum())

import pandas as pd

# Step 1: Convert timestamp to datetime and extract date and hour components
df['timestamp'] = pd.to_datetime(df['timestamp']) # Convert timestamp column to datetime format

df['date'] = df['timestamp'].dt.date # Extract the date part only
df['hour'] = df['timestamp'].dt.hour # Extract the hour part only

# Task 1: Calculate the daily average temperature
daily_avg_temp = df.groupby('date')['temperature_C'].mean() # Group data by date and find mean temperature
print("1. Daily Average Temperature (C):")
print(daily_avg_temp.round(2)) # Display results rounded to 2 decimal places
print("-" * 40) # Print a separator line

# Task 2: Calculate min, max, and mean for all key weather metrics
metrics_summary = df[['temperature_C', 'humidity_%', 'wind_speed_kmph', 'pressure_hPa', 'visibility_km']].agg(['min', 'max', 'mean']) # Aggregate statistics
print("2. Min, Max, and Mean for Each Metric:")
print(metrics_summary.round(2)) # Display results rounded to 2 decimal places
print("-" * 40) # Print a separator line

# Task 3: Identify the hour with the highest average humidity
max_humidity_value = df['humidity_%'].max() # Find the maximum humidity value in the dataset
max_humidity_row = df.loc[df['humidity_%'].idxmax()] # Get the entire row where humidity is maximum

peak_hour = max_humidity_row['timestamp'].hour # Extract the hour from that timestamp
peak_timestamp = max_humidity_row['timestamp'] # Get the full timestamp

# Print the final result in a professional format
print("3. Maximum Humidity Recorded:")
print(f"Result: The highest humidity was {max_humidity_value}% at Hour {peak_hour}:00, on {peak_timestamp}")

#TODO: Extract temperature and wind_speed as NumPy arrays
import numpy as np

temp = df['temperature_C'].to_numpy()
wind = df['wind_speed_kmph'].to_numpy()
print("Temperature Array:", temp.shape, "Type:", type(temp))
print("Wind Array:", wind.shape, "Type:", type(wind))
#3333print("First 5 Temp values:", temp[:5])
#print("First 5 Wind values:", wind[:5])

# TODO: Reshape and aggregate
temp_matrix = temp.reshape((10, 24))
print("1. Temp Matrix Shape:", temp_matrix.shape)
delay_min=np.nanmin(temp_matrix, axis=1)
daily_max = np.nanmax(temp_matrix, axis=1)
daily_mean = np.nanmean(temp_matrix, axis=1)

print("2. Every day temp:")
print("Daily Min:", delay_min.round(2))
print("Daily Max:", daily_max.round(2))
print("Daily Mean:", daily_mean.round(2))

import numpy as np

temp_matrix = df.pivot_table(index='date', columns='hour', values='temperature_C')
print("1. Original Temp Matrix Shape:", temp_matrix.shape)
print(temp_matrix.round(2))



def normalize(matrix):
    mean = np.nanmean(matrix)
    std = np.nanstd(matrix)
    normalized_matrix = (matrix - mean) / std
    return normalized_matrix


normalized_temp = normalize(temp_matrix)

print("2. Normalized Temp Matrix:")
print("Formula: (Value - Mean) / Std Dev")
print(normalized_temp.round(2))
print("-"*40)
print(f"Check: Mean = {np.nanmean(normalized_temp):.2f}, Std = {np.nanstd(normalized_temp):.2f}")
temp_matrix = df.pivot_table(index='date', columns='hour', values='temperature_C')
print("1. Original Temp Matrix Shape:", temp_matrix.shape)
print(temp_matrix.round(2))

print("="*40)
print("STEP C: MASK / FILTER")
print("="*40)

# 1. Create a boolean mask for wind speed > 15 kmph
# Mask = True/False ka array. Jahan True hoga matlab Wind > 15 hai
mask = wind > 15
print("1. Mask ban gaya. Total True values:", mask.sum())
print("-"*40)

# 2. Use it to extract high-wind readings
high_wind = wind[mask]
print("2. High Wind Readings > 15 kmph:")
print(high_wind)
print(f"Total High-Wind Records: {len(high_wind)}")
print(f"Max Wind in these: {high_wind.max():.2f} kmph")

import numpy as np
import pandas as pd # Table ke liye

def daily_summary(matrix: np.ndarray):
    summaries = []
    for i in range(matrix.shape[0]):
        day_data = matrix[i, :]
        summaries.append({
            'Day': i + 1,
            'Min_C': float(np.nanmin(day_data).round(2)),
            'Max_C': float(np.nanmax(day_data).round(2)),
            'Mean_C': float(np.nanmean(day_data).round(2))
        })
    return pd.DataFrame(summaries)


if type(temp_matrix)!= np.ndarray:
    temp_matrix = temp_matrix.to_numpy()

result_df = daily_summary(temp_matrix)

print("Daily Temperature Summary Report")
print(result_df.to_string(index=False))

import pandas as pd # Import pandas library to work with data tables

# Step 1: Load data and clean missing values
df = pd.read_csv('hourly_weather_10_days.csv')# Read data from the Excel file into a DataFrame

# List all columns that contain numeric weather data
numeric_columns = ['temperature_C', 'humidity_%', 'wind_speed_kmph', 'pressure_hPa', 'visibility_km']

# Fill missing values by carrying the last valid value forward
df[numeric_columns] = df[numeric_columns].ffill()

# Fill any remaining missing values at the start by carrying the next valid value backward
df[numeric_columns] = df[numeric_columns].bfill()

# Step 2: Convert timestamp column to datetime format
df['timestamp'] = pd.to_datetime(df['timestamp'])

# Set the timestamp column as the index for fast date-time lookup
df = df.set_index('timestamp')

# Step 3: Define a function to get weather data for a given date and time
def get_weather(date_time):
    """
    Retrieves and displays weather data for a specific date and time.

    Args:
        date_time (str): Date and time in 'DD/MM/YYYY HH:MM' format.
    """
    # Convert the user input string to a datetime object
    search_time = pd.to_datetime(date_time, format='%d/%m/%Y %H:%M')

    # Check if the requested datetime exists in the dataset index
    if search_time in df.index:
        # Retrieve the row of data for the given timestamp
        record = df.loc[search_time]

        # Print the formatted weather report header
        print(f"\nWeather Report for {search_time.strftime('%d %b %Y, %H:%M')}")
        print("-" * 45) # Print a separator line

        # Print each weather parameter with 2 decimal places
        print(f"Temperature : {record['temperature_C']:.2f} C")
        print(f"Humidity : {record['humidity_%']:.2f} %")
        print(f"Wind Speed : {record['wind_speed_kmph']:.2f} km/h")
        print(f"Pressure : {record['pressure_hPa']:.2f} hPa")
        print(f"Visibility : {record['visibility_km']:.2f} km")
    else:
        # Print an error if the date and time is not found
        print("Error: Data not found for the specified date and time.")

# Step 4: Take input from the user at runtime
user_input = input("Enter date and time (DD/MM/YYYY HH:MM): ") # Ask user for date and time

# Call the function with the user input
get_weather(user_input)