# -*- coding: utf-8 -*-
"""Assignment  1.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dF89nGrzzdZx9JglsyrAeHB5p_jQlPS
"""

import sys

import numpy as np

import pandas as pd

print("Python:",sys.version)

print("Numpy:",np.__version__)

print("Pandas:",pd.__version__)

