# -*- coding: utf-8 -*-
"""Assignment_2_pynb (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194TQaDBnZno13-hMzyr-prLBzAnx9M4v
"""

# TODO: Define a string, integer, float, and boolean
# Hint: Use type() to verify the type of each variable
name = 'Alice'  # e.g., 'Alice'
age = 0    # e.g., 25
height = 0.0  # e.g., 5.7
is_student = False

# Print each variable and its type

print("Name:", name, "| Type:", type(name))
print("Age:", age, "| Type:", type(age))
print("Height:", height, "| Type:", type(height))
print("Is Student:", is_student, "| Type:", type(is_student))

# Asking user to enter a score (0-100)
score = int(input("Enter your score: "))

# Grading logic using an if-elif-else ladder
if score < 0 or score > 100:
    print("Invalid score! Please enter a value between 0 and 100.")
elif score >= 90:
    print("Grade: A")
elif score >= 80:
    print("Grade: B")
elif score >= 70:
    print("Grade: C")
elif score >= 60:
    print("Grade: D")
else:
    print("Grade: F")

# TODO: Print a right-angled triangle using '*'
n = 5  # height of triangle
for i in range(1, n+1):
    print('*' * i)

# MY WORK
# Height of the triangle
n = 5

# Outer loop for rows
for i in range(1, n + 1):
    # Inner loop for printing stars in each row
    for j in range(i):
        print('*', end=' ')
    # Move to the next line after finishing the row
    print()

# Create a list of squares from 1 to 10 using list comprehension
squares = [x**2 for x in range(1, 11)]

# Printing the result
print(squares)

# 1. Tuple creation
sample_tuple = (10, 20, 30, 40, 50)


sample_set = set()
sample_set.add('apple')
sample_set.add('banana')
print(hash('apple'))
print(hash('banana'))



# 3. Dictionary creation
sample_dict = {'name': 'Alice', 'age': 25}
sample_dict['city']='Lahore'
del sample_dict['age']

# Printing the data structures
print("Tuple:", sample_tuple)
print("Set:", sample_set)
print("Dictionary:", sample_dict)# 1. Tuple creation

# The input text
text = "Python is simple yet powerful. Python is easy to learn."

# Cleaning the text by removing periods and converting to lowercase
cleaned_text = text.replace(".", "").lower()

# Splitting the text into individual words
words = cleaned_text.split()

# Empty dictionary to store word counts
word_freq = {}

# Logic to count words
for word in words:
    if word in word_freq:
        word_freq[word] += 1  # If word exists, increase count by 1
    else:
        word_freq[word] = 1   # If word is new, set count to 1

# Printing the result
print(word_freq)

#Defining a function that appends an item to a list
def modify_list(my_list):
    # This directly changes the original list because lists are mutable
    my_list.append("new item")

# Initializing the original list
lst = ["item1", "item2"]

# Passing the list to the function
modify_list(lst)

# Printing the list to observe the changes
print(lst)