# -*- coding: utf-8 -*-
"""Numpy and plotting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_JMZa4pmMfwcZ3nJmYxvK4w3bTA0zh45
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt

# %matplotlib inline

x = np.array([1, 2.5, 5, 10])
print(x,type(x))

y = np.random.rand(4)
print(y,type(y))

plt.figure()

plt.plot(x,y, 'g', label='y(x)')

plt.legend(loc='lower right')
plt.xlabel('x')
plt.ylabel('y')
plt.title('Sample Figure')
plt.xlim([0, 10])
plt.ylim([0, 1])
plt.savefig('sample.png')
plt.show()

M = np.array([[0.25, 6.2, 1, 10],[12, 6.2, 6, -5.3]])
print(M,type(M))

print(x,type(x))

print(x.size)  # or equivalently np.size(x)
print(M.size)

print(x)
print(x[2],x[-1])
print(x[::-1])
x[0] = 6.1554
print(x)

v = x
w = np.copy(x)
print(v)
x[0]=1
print(v)
print(w)

print(M)
print(M[1,2],type(M[1,2]))
print(M[1,:],type(M[1,:]),M[1,:].shape)
print(M[1])
print(M[:,0])

x = np.array([1, 2.5, 5, 10])
ind = [0,2,3]
print(x[ind])

print(x.dtype)

try:
    x[0] = 1 + 2.0j
except Exception as e:
    print(e)

y = x.astype(complex)
y[0] = 1 + 2.0j
print(y,type(y),y.dtype)

x = np.arange(0, 10, 1.5)
print(x,type(x))

y = np.linspace(0, 10, 25)
print(y,type(y))

x = np.zeros(3)
print(x,x.shape,type(x),x.dtype)

x = np.zeros((3,))
print(x,x.shape,type(x),x.dtype)

try:
    x = np.zeros(3,3) # This causes an error as 3,3 is not a shape, it is (3,3) -> double parentheses
except Exception as error:
    print(error)

print(x,x.shape,type(x),x.dtype)

x = np.zeros((3,3))
print(x,x.shape,type(x),x.dtype)

y = np.ones(2)
y

M = np.eye(3)
print(M,M.shape,type(M),M.dtype)

np.random.rand(5)

np.random.randn(5,2)

np.random.randint(0,100,size=(10,))

a = np.random.randn(10000)
plt.figure()
plt.hist(a,40) # histogram of a with 40 bins
plt.show()

v = np.arange(0, 5)
print(v)

v * 2

v + 2.5

square = v**2
root = np.sqrt(v)
print(square,root)

plt.figure()
plt.subplot(1,2,1)
plt.plot(square,'g--', label='$y = x^2$')
plt.legend(loc=0)
plt.subplot(1,2,2)
plt.plot(root, 'r*-', label='$y = \sqrt{x}$')
plt.legend(loc=2)
plt.show()

A = np.array([[n+m*10 for n in range(5)] for m in range(4)])
print(A)

A*2

A+2.5

C = np.random.randn(100,100)
plt.figure()
plt.imshow(C)
plt.colorbar()
plt.show()

A = np.array([[n+m*10 for n in range(5)] for m in range(4)])
v = np.random.randint(0,5,5)
print(A,v)

A*A

v*v

A*v

print(A,A.shape)
print(A.T,A.T.shape)

y = np.dot(A,v)
print(A,A.shape,v,v.shape)
print(y,type(y),y.shape)

s = v.dot(v)
print(v, s, type(s))

try:
    A2 = np.dot(A,A)
except Exception as error:
    print(error)

A3 = np.dot(A,A.T)
print(A3,A3.shape)

P = np.outer(v,v)
print(P)

A.reshape((2,10))

print(A)

B = A.flatten()
print(B)

print(A.trace(),A.max(),A.argmax())

print(A.mean(),A.mean(axis=0),A.mean(axis=1))

print(A.var(),A.var(axis=0),A.std(axis=1))

a = np.array([[1, 2], [3, 4]])
a

b = np.array([[5, 6]])
b

np.concatenate((a, b), axis=0)

np.concatenate((a, b.T), axis=1)

np.vstack((a,b))

np.hstack((a,b.T))

v = np.array([1,2,3,4])

for element in v:
    print(element)

a = np.array([[1,2], [3,4]])

for row in a:
    print("row", row)

    for element in row:
        print(element)

for row_idx, row in enumerate(a):
    print("row_idx", row_idx, "row", row)

    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)

        # update the matrix a: square each element
        a[row_idx, col_idx] = element ** 2

a

A = np.random.randn(3,2)

Q, R = np.linalg.qr(A)
print(A)
print(Q)
print(R)

np.allclose(A, np.dot(Q, R)) # check that A=QR

U, s, V = np.linalg.svd(A)
print(U.shape, V.shape, s.shape)

S = np.zeros(A.shape)
S[:A.shape[1], :A.shape[1]] = np.diag(s)
np.allclose(A, np.dot(U, np.dot(S, V)))

U, s, V = np.linalg.svd(A, full_matrices=False)
print(U.shape, V.shape, s.shape)

S = np.diag(s)
np.allclose(A, np.dot(U, np.dot(S, V)))

A = np.array([[1, -1], [1, 1]])
print(A)
l, v = np.linalg.eig(A)
print(l); print(v)

A.dot(v[:,0])

np.allclose(A.dot(v[:,0]),l[0]*v[:,0])

a = np.arange(9) - 4
B = a.reshape((3, 3))

print(a)
print("none \t",np.linalg.norm(a))
print("2 \t",np.linalg.norm(a,ord=2))
print("1 \t",np.linalg.norm(a,ord=1))
print("inf \t",np.linalg.norm(a,ord=np.inf))
print("0 \t",np.linalg.norm(a,ord=0))

print(B)
print("none \t",np.linalg.norm(B))
print("2 \t",np.linalg.norm(B,ord=2))
print("1 \t",np.linalg.norm(B,ord=1))
print("inf \t",np.linalg.norm(B,ord=np.inf))
print("fro \t",np.linalg.norm(B,ord='fro'))

A = np.array([[1, 0, -1], [0, 1, 0], [1, 0, 1]]) # some matrix
I = np.eye(4) # identity
Def =  np.eye(4); Def[0,0]=0 # rank deficient

print(np.linalg.cond(A), np.linalg.cond(I))

np.linalg.cond(Def)

print(np.linalg.matrix_rank(A), np.linalg.matrix_rank(I), np.linalg.matrix_rank(Def))

v

#Create a NumPy array of integers from 1 to 10.

#Use the .reshape() method to change the shape of the array to a 2x5 matrix.

import numpy as np

# Create a NumPy array of integers from 1 to 10
arr = np.arange(1, 11)
print("Original array:", arr)

# Reshape the array to a 2x5 matrix
reshaped_arr = arr.reshape(2, 5)
print("Reshaped array (2x5):")
print(reshaped_arr)

#Create a 5x5 NumPy array filled with random integers between 1 and 100.

#Extract the middle 3x3 section of the array using slicing.

import numpy as np

# Create a 5x5 NumPy array filled with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(5, 5))
print("Original 5x5 array:")
print(arr)

# Extract the middle 3x3 section using slicing
middle_section = arr[1:4, 1:4]
print("\nMiddle 3x3 section:")
print(middle_section)

#Given two arrays: a = np.array([1, 2, 3, 4, 5]) and b = np.array([6, 7, 8, 9, 10]), compute the element-wise sum, difference, product, and division of a and b.

import numpy as np

# Given arrays
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

# Element-wise operations
sum_result = a + b
diff_result = a - b
product_result = a * b
division_result = a / b

print("Array a:", a)
print("Array b:", b)
print("\nElement-wise Sum:", sum_result)
print("Element-wise Difference (a - b):", diff_result)
print("Element-wise Product:", product_result)
print("Element-wise Division (a / b):", division_result)

#Plot the sine wave for x values ranging from 0 to 2*pi. Use 100 points and display the plot with appropriate labels for the x and y axes.

import numpy as np
import matplotlib.pyplot as plt

# Generate 100 points from 0 to 2*pi
x = np.linspace(0, 2 * np.pi, 100)
y = np.sin(x)

# Plot the sine wave
plt.plot(x, y)
plt.title("Sine Wave")
plt.xlabel("x (radians)")
plt.ylabel("sin(x)")
plt.grid(True)
plt.show()

#Create a 2x2 subplot layout in Matplotlib and display the following in each subplot:

#A line plot of y = x^2.

#A scatter plot of random points.

#A bar chart of some arbitrary data.

#A histogram of random numbers.

import numpy as np
import matplotlib.pyplot as plt

# Create a 2x2 subplot layout
fig, axs = plt.subplots(2, 2, figsize=(10, 8))

# 1. Line plot of y = x^2
x = np.linspace(-10, 10, 100)
y = x ** 2
axs[0, 0].plot(x, y, color='blue')
axs[0, 0].set_title("Line Plot: y = x^2")
axs[0, 0].set_xlabel("x")
axs[0, 0].set_ylabel("y")

# 2. Scatter plot of random points
x_scatter = np.random.rand(50)
y_scatter = np.random.rand(50)
axs[0, 1].scatter(x_scatter, y_scatter, color='green')
axs[0, 1].set_title("Scatter Plot: Random Points")
axs[0, 1].set_xlabel("x")
axs[0, 1].set_ylabel("y")

# 3. Bar chart of arbitrary data
categories = ['A', 'B', 'C', 'D']
values = [23, 45, 12, 36]
axs[1, 0].bar(categories, values, color='orange')
axs[1, 0].set_title("Bar Chart: Arbitrary Data")
axs[1, 0].set_xlabel("Category")
axs[1, 0].set_ylabel("Value")

# 4. Histogram of random numbers
random_data = np.random.randn(1000)
axs[1, 1].hist(random_data, bins=30, color='purple')
axs[1, 1].set_title("Histogram: Random Numbers")
axs[1, 1].set_xlabel("Value")
axs[1, 1].set_ylabel("Frequency")

# Adjust layout so titles/labels don't overlap
plt.tight_layout()
plt.show()

#Create a NumPy array of 50 random numbers. Use np.mean(), np.median(), and np.std() to compute the mean, median, and standard deviation of the array.

import numpy as np

# Create a NumPy array of 50 random numbers
arr = np.random.rand(50) * 100  # random numbers between 0 and 100

print("Array of 50 random numbers:")
print(arr)

# Compute mean, median, and standard deviation
mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)

print("\nMean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_val)

#Plot a pie chart showing the distribution of data in a given list of categories, e.g., ['Math', 'Science', 'History', 'English'], with random values for each category.

import matplotlib.pyplot as plt
import random

categories = ['Math', 'Science', 'History', 'English']
values = [random.randint(10, 100) for i in range(4)]

plt.pie(values, labels=categories)
plt.title(" Distribution")
plt.show()

#Create a 3x3 matrix filled with random integers between 1 and 10.

#Transpose the matrix and then find the sum of each column.

import numpy as np

# Create a 3x3 matrix filled with random integers between 1 and 10
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original Matrix:")
print(matrix)

# Transpose the matrix
transposed = matrix.T
print("\nTransposed Matrix:")
print(transposed)

# Sum of each column (of transposed matrix)
column_sums = np.sum(transposed, axis=0)
print("\nSum of each column:", column_sums)

#Write a function that takes a NumPy array and returns the array after squaring all the elements.

import numpy as np

def square_array(arr):
    return arr ** 2

# Example usage
my_array = np.array([1, 2, 3, 4, 5])
result = square_array(my_array)

print("Original array:", my_array)
print("Squared array:", result)

#Create a 5x5 NumPy array with random values and introduce some NaN (Not a Number) values.

#Use NumPy functions to fill in the NaN values with the column mean of the array.

import numpy as np

# Create a 5x5 array with random values
arr = np.random.randint(1, 50, size=(5, 5)).astype(float)

# Introduce some NaN values manually
arr[1, 2] = np.nan
arr[3, 4] = np.nan
arr[0, 0] = np.nan

print("Original array with NaN values:")
print(arr)

# Fill NaN values with column mean
col_mean = np.nanmean(arr, axis=0)

# Find indices where NaN is present and replace with column mean
inds = np.where(np.isnan(arr))
arr[inds] = np.take(col_mean, inds[1])

print("\nArray after filling NaN with column mean:")
print(arr)