# -*- coding: utf-8 -*-
"""Python hands on.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QY_oRj9yM5pZN60I9_XaOALN4bEaT_PT
"""

import pandas as pd
import numpy as np

data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

print(data[0],type(data[0]))

print(data[2:],type(data[2:]))

print(data.values,type(data.values))

print(data.index,type(data.index))

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
print(data)

print(data['c'])

data = pd.Series([0.25, 0.5, 0.75, 1.0], index=[1, 3, 4, 2])
print(data)

print(data[2])

population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
print(population_dict,type(population_dict))
print(population,type(population))

population['California']

population['California':'Illinois']

area = pd.Series( {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995})
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135})

states = pd.DataFrame({'Population': population, 'Area': area})
print(states,type(states))

states

print(states.index)
print(states.columns)
print(states.values,type(states.values),states.values.shape)

print(states['Area'],type(states['Area']))

try:
    print(states['California'])
except KeyError as error:
    print("KeyError: ",error)

print(population,type(population))
states = pd.DataFrame({'Population': population, 'Area': area})
states

A = np.random.randn(5,3)
print(A,type(A))
dfA = pd.DataFrame(A)
dfA

data = [{'a': i, 'b': 2 * i} for i in range(3)]
print(data,type(data))
print(data[0],type(data[0]))

df = pd.DataFrame(data)
df

!head -4 president_heights.csv # bash command to see the first 4 lines of the file

data = pd.read_csv('president_heights.csv')
data

# @title order vs height(cm)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['order']
  ys = series['height(cm)']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = data.sort_values('order', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('order')
_ = plt.ylabel('height(cm)')

# @title order vs height(cm)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['order']
  ys = series['height(cm)']

  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = data.sort_values('order', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('order')
_ = plt.ylabel('height(cm)')

pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

dfA.columns = ['a','b','c']
dfA.index = [i**2 for i in range(1,6)  ]
dfA

import numpy as np
dfA=pd.DataFrame(np.random.randn(5,3))
dfA.columns=['a','b','c']
dfA.index=[i**2 for i in range(1,6)]
dfA

area = pd.Series( {'California': 423967, 'Texas': 695662, 'New York': 141297, 'Florida': 170312, 'Illinois': 149995})
population = pd.Series({'California': 38332521, 'Texas': 26448193, 'New York': 19651127, 'Florida': 19552860, 'Illinois': 12882135})
states = pd.DataFrame({'Population': population, 'Area': area})
states

vvvvv

# @title Population vs Area

from matplotlib import pyplot as plt
states.plot(kind='scatter', x='Population', y='Area', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

states['Area']

states['Area']['Texas']

states.iloc[:2]

states.loc[:'New York']

states.loc[:,'Population':]

# QUESTION NO 1     SERIES

# Create a Pandas Series
series = pd.Series([10, 20, 30, 40, 50])
print("Series:")
print(series)

# Access the third element (index starts from 0)
print("\nThird element:", series[2])

# Data type of the Series
print("\nData type:", series.dtype)

# QUESTION NO 2 DataFrames

# Create a DataFrame with Name and Age columns
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
}
df = pd.DataFrame(data)
print("DataFrame:")
print(df)

# Access the 'Age' column
print("\nAge column:")
print(df['Age'])

# Shape of the DataFrame
print("\nShape of DataFrame:", df.shape)

# QUESTION NO 3 Indexing

# Access row with name 'Bob' using loc (Bob is at index 1)
print("Row with Bob (loc):")
print(df.loc[1])

# Access age of 'Alice' using iloc (Alice is row 0, Age is column 1)
print("\nAge of Alice (iloc):", df.iloc[0, 1])

# QUESION  NO 4 . File I/O.

# Read the CSV file
president_df = pd.read_csv('president_heights.csv')
print("First 5 rows of president_heights.csv:")
print(president_df.head())

# Average height of presidents
print("\nAverage height:", president_df['height(cm)'].mean())

# Name of the tallest president
tallest = president_df.loc[president_df['height(cm)'].idxmax()]
print("\nTallest president:", tallest['name'])

##  QUESTION NO 5 ADVANCED

# Create a DataFrame with random numbers in columns A, B, C
df2 = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C'])
print("DataFrame with random numbers:")
print(df2)

# Mean of each column
print("\nMean of each column:")
print(df2.mean())

# Add column D as sum of A and B
df2['D'] = df2['A'] + df2['B']
print("\nDataFrame with column D:")
print(df2)

# Sort by column D in descending order
sorted_df = df2.sort_values(by='D', ascending=False)
print("\nSorted DataFrame by D (descending):")
print(sorted_df)